export enum Tags {
    A = 'a',
    BUTTON = 'button',
    DIV = 'div',
    H3 = 'h3',
    SPAN = 'span',
    TP_YT_IRON_DROPDOWN = 'tp-yt-iron-dropdown',
    TP_YT_PAPER_CHECKBOX = 'tp-yt-paper-checkbox',
    TP_YT_PAPER_DIALOG = 'tp-yt-paper-dialog',
    TP_YT_PAPER_ITEM = 'tp-yt-paper-item',
    TP_YT_PAPER_LISTBOX = 'tp-yt-paper-listbox',
    YTD_ADD_TO_PLAYLIST_RENDERER = 'ytd-add-to-playlist-renderer',
    YTD_APP = 'ytd-app',
    YTD_BROWSE = 'ytd-browse',
    YTD_BUTTON_RENDERER = 'ytd-button-renderer',
    YTD_ITEM_SECTION_RENDERER = 'ytd-item-section-renderer',
    YTD_MENU_POPUP_RENDERER = 'ytd-menu-popup-renderer',
    YTD_MENU_RENDERER = 'ytd-menu-renderer',
    YTD_MENU_SERVICE_ITEM_RENDERER = 'ytd-menu-service-item-renderer',
    YTD_PAGE_MANAGER = 'ytd-page-manager',
    YTD_PLAYLIST_ADD_TO_OPTION_RENDERER = 'ytd-playlist-add-to-option-renderer',
    YTD_PLAYLIST_PANEL_RENDERER = 'ytd-playlist-panel-renderer',
    YTD_PLAYLIST_PANEL_VIDEO_RENDERER = 'ytd-playlist-panel-video-renderer',
    YTD_PLAYLIST_VIDEO_LIST_RENDERER = 'ytd-playlist-video-list-renderer',
    YTD_PLAYLIST_VIDEO_RENDERER = 'ytd-playlist-video-renderer',
    YTD_POPUP_CONTAINER = 'ytd-popup-container',
    YTD_RICH_GRID_MEDIA = 'ytd-rich-grid-media',
    YTD_RICH_GRID_RENDERER = 'ytd-rich-grid-renderer',
    YTD_RICH_GRID_ROW = 'ytd-rich-grid-row',
    YTD_RICH_ITEM_RENDERER = 'ytd-rich-item-renderer',
    YTD_SECTION_LIST_RENDERER = 'ytd-section-list-renderer',
    YTD_TWO_COLUMN_BROWSE_RESULTS_RENDERER = 'ytd-two-column-browse-results-renderer',
    YTD_VIDEO_META_BLOCK = 'ytd-video-meta-block',
    YTD_WATCH_FLEXY = 'ytd-watch-flexy',
    YTD_WATCH_METADATA = 'ytd-watch-metadata',
    YT_FORMATTED_STRING = 'yt-formatted-string',
    YT_ICON = 'yt-icon',
    YT_ICON_BUTTON = 'yt-icon-button'
}

export enum Ids {
    ABOVE_THE_FOLD = 'above-the-fold',
    ACTIONS = 'actions',
    ACTIONS_INNER = 'actions-inner',
    BELOW = 'below',
    BUTTON = 'button',
    CHECKBOX = 'checkbox',
    CHECKBOX_CONTAINER = 'checkbox-container',
    CHECKBOX_LABEL = 'checkbox-label',
    CHECKBOX_LABEL_CAMEL_CASE = 'checkboxLabel',
    COLUMNS = 'columns',
    CONTAINER = 'container',
    CONTENT = 'content',
    CONTENTS = 'contents',
    CONTENT_WRAPPER_CAMEL_CASE = 'contentWrapper',
    DETAILS = 'details',
    DISMISSIBLE = 'dismissible',
    FLEXIBLE_ITEM_BUTTONS = 'flexible-item-buttons',
    ITEMS = 'items',
    LABEL = 'label',
    MENU = 'menu',
    META = 'meta',
    PAGE_MANAGER = 'page-manager',
    PLAYLIST = 'playlist',
    PLAYLISTS = 'playlists',
    PLAYLIST_ITEMS = 'playlist-items',
    PRIMARY = 'primary',
    PRIMARY_INNER = 'primary-inner',
    SECONDARY = 'secondary',
    SECONDARY_INNER = 'secondary-inner',
    TEXT = 'text',
    TOP_LEVEL_BUTTONS_COMPUTED = 'top-level-buttons-computed',
    TOP_ROW = 'top-row',
    YT_QUICK_ACTIONS_HOME_WATCH_LATER = 'yt-quick-actions-home-watch-later',
    YT_QUICK_ACTIONS_REMOVE_BUTTON = 'yt-quick-actions-remove-button',
    YT_QUICK_ACTIONS_VIDEO_WATCH_LATER = 'yt-quick-actions-video-watch-later'
}

export enum TextContent {
    // The trailing whitespace is intentional and required!
    REMOVE_FROM = 'Remove from ',
    REMOVE_FROM_LOWERCASE = 'remove from',
    REMOVE_FROM_PLAYLIST = 'Remove from playlist',
    SAVE = 'Save',
    SAVE_TO_WATCH_LATER = 'Save to Watch later',
    WATCH_LATER = 'Watch later'
}

export enum AttributeNames {
    HIDDEN = 'hidden',
    DISABLE_UPGRADE = 'disable-upgrade',
}