autolabeler:
  - label: "bug"
    branch:
      - "/^fix/"
      - "/^bugfix/"
    title:
      - "/^fix/i"
      - "/^bugfix/i"
  - label: "enhancement"
    branch:
      - "/^feature/"
    title:
      - "/^feature/i"
categories:
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
exclude-labels:
  - "skip-changelog"
category-template: "### $TITLE"
change-template: "- $TITLE @$AUTHOR ([#$NUMBER]($URL))"
change-title-escapes: '\<*_&#@'
no-changes-template: "- No Changes"
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
